# Load standard libraries
library(ggplot2)
library(gplots)
library(RColorBrewer)
library(tidyr)
library(reshape2)
library(stringi)
library(readxl)
library(dplyr)
library(plyr)
library(Biobase)
library(seqinr)
library(lattice)
library(BALCONY)
library(processx)

# READ alignment files ###################################################
dir_name <-dirname(rstudioapi::getSourceEditorContext()$path)
# dir_name <- "C:/Your_filepath_here"
setwd(dir_name)

# Read the alignment file to be analyzed. In this case a CLustal MSA of the heterologous LipAs tested in vivo
alignmentfile <- read.alignment(file="alignments/alignment_all_LipAs.clustal_num", format = "clustal")

# Complementing
compseq <- c(1,3,5,7,11,13,14,15,16)
alignmentfile$nam[compseq]
# Non-complementing
nonComp<-c(2,4,6,8,9,10,12)
alignmentfile$nam[nonComp]

# Test the difference in sequences between the two groups################ 
# Convert to matrix for workability
matalign <- as.matrix(alignmentfile)

#A vector with the majority amino acids of the complementing sequences
compseq_major <- consensus(matalign[compseq,], method = "majority")

# For each stop in the majority consensus, test is the AA is the same in each non complementing seq
# and count how many are the same (max 7):
comp_noncomp_diff <- c()

for (pos in 1:length(compseq_major)){
  sameAA <- 0 
  for (seqnum in 1:length(nonComp)){
    if (matalign[seqnum,pos] == compseq_major[pos]){
      sameAA = sameAA + 1
    }
  }
  comp_noncomp_diff <- c(comp_noncomp_diff,sameAA)
}


# Transform to percentage:
comp_noncomp_diff <- comp_noncomp_diff/7

# Which positions have low similarity? Combine in new matrix
matalign_new <- rbind(matalign, comp_noncomp_diff) 
matalign_new <- rbind(matalign_new, comp_noncomp_diff == 0) 

# How many positions of the non-comp have 0 resdiues in common with the majority consensus of the complementing?
ncol(matalign_new[,matalign_new[18,]==TRUE])
consensus(matalign_new[1:16,matalign_new[18,]==TRUE], method = "IUPAC")

# Made a 1d heatmap (color gradient) of this data
df <- data.frame(x=1:ncol(matalign_new),freq=matalign_new[17,])
newdf=data.frame(x=spline(df)[[1]],freq=spline(df)[[2]],y=rep(1,times=3*length(df$x)))
levelplot(freq~x*y,data=newdf)
ggplot(newdf,aes(x=x,y=y,fill=freq))+geom_tile()



ggplot(df, aes(x, freq)) + geom_point() +
  geom_smooth(method = "gam", formula = y ~ poly(x, 2)) 
ggplot(df, aes(x, freq)) + geom_point() +
  geom_smooth(method = "loess", span = 0.3, se = FALSE) 


library(plotly)
p <- plot_ly(x = df$x, y = df$freq, type = 'scatter', mode = 'lines', fill = 'tozeroy')%>%
  layout(xaxis = list(title = 'Alignment Position'),
         yaxis = list(title = 'Conservation'))
p



# Gather just the residues of mtLipA and the values for conservation, for further mapping
mtLipA_residues <-matalign_new[c(3,17),(matalign_new[3,]!="-"  & matalign_new[3,]!="\t")]

mtLipA_nocons<-mtLipA_residues[,mtLipA_residues[2,]==0]


p <- plot_ly(x = 1:length(mtLipA_residues), y = c(mtLipA_residues[2,]), type = 'scatter', mode = 'lines', fill = 'tozeroy')%>%
  layout(xaxis = list(title = 'Alignment Position'),
         yaxis = list(title = 'Conservation'))
p


position = 15
threshold = 0.01
var_aa = calculate_AA_variation(small_alignment,threshold)
barplotshow(position, var_aa)


######## NEW ANALYSIS #####################
# Do conservation of alignment of mtLipA with conmplementing LipAs and one with non-complementing AA
# Data generated with ConSurf amino acid conservation scoreing data, for all 16 LipAs and for just the complementing LipAs

# Read in the conservation scores generated by ConSurf:
conscore_all<-read.csv("Alignments/Allalign_to_mtLipA_alignscores.tab", sep ="")
conscore_complement <-read.csv("Alignments/CompAlign_to_mtLipA_alignscores.tab", sep ="")

# Turn the normalized conservation scores into an obsolute score for easier visualization
conscore_all$SCORE_abs <- (1/2^conscore_all$SCORE_norm)
conscore_all$SCORE_abs <- conscore_all$SCORE_abs/max(conscore_all$SCORE_abs)

conscore_complement$SCORE_abs <- (1/2^conscore_complement$SCORE_norm)
conscore_complement$SCORE_abs <- conscore_complement$SCORE_abs/max(conscore_complement$SCORE_abs)

# Combine in one dataframe for easier manipulation
consDF <- data.frame(pos = conscore_all$POS, seq =conscore_all$SEQ, CONS_all = conscore_all$SCORE_abs, CONS_comp = conscore_complement$SCORE_abs)

consDF$DIFF <- (consDF$CONS_comp-consDF$CONS_all)

#Is the difference in conservation score significant? If there is no over-lap of confidence interval between
# THe two, then it is. The confidence interval is given one colum $CONFIDENCE. It needs to be split in two 
# To be used further

for (n in 1:nrow(conscore_all)){
  conscore_all$LOW_conf[n] <- as.numeric(strsplit(as.character(conscore_all$CONFIDENCE[n]), split = ",")[[1]][1])
  conscore_all$UP_conf[n] <- as.numeric(strsplit(as.character(conscore_all$CONFIDENCE[n]), split = ",")[[1]][2])
  
  conscore_complement$LOW_conf[n] <- as.numeric(strsplit(as.character(conscore_complement$CONFIDENCE[n]), split = ",")[[1]][1])
  conscore_complement$UP_conf[n] <- as.numeric(strsplit(as.character(conscore_complement$CONFIDENCE[n]), split = ",")[[1]][2])
}

consDF$SIG <- rep("na", nrow(consDF))
write.csv(consDF, "Conservation_CompvsNoncomp_mtLipA.csv")
# Test if the ranges overlap, if they don't then mark the SIG column of consDF as FLASE, if they do then TRUE
for (n in 1:nrow(consDF)){ 
  if(((conscore_complement$LOW_conf[n] > conscore_all$UP_conf[n]) & (conscore_complement$UP_conf[n] > conscore_all$UP_conf[n])) | ((conscore_complement$LOW_conf[n] < conscore_all$LOW_conf[n]) & (conscore_complement$UP_conf[n] < conscore_all$LOW_conf[n]))){
    consDF$SIG[n] <- TRUE
  }else{
    consDF$SIG[n] <- FALSE
  }
}





# Make a dataframe with only significantly different residues. 16 residues are significant
consDF_SIG <- consDF[consDF$SIG == TRUE,]
nrow(consDF_SIG)
# Make three separate dataframe, each with 1/3 of the values for labeling the plot
CDS1<-consDF_SIG[seq(1, nrow(consDF_SIG), 3), ]
CDS2<-consDF_SIG[seq(1+1, nrow(consDF_SIG), 3), ]
CDS3<-consDF_SIG[seq(1+2, nrow(consDF_SIG), 3), ]

# Make a combined plot showing difference in conservation between the two and also which are significant, lableing these
p1 <- plot_ly(x = consDF$pos, y = consDF$DIFF, type = 'scatter', fill = 'tozeroy', mode = "lines")%>%
  add_annotations(x = consDF_SIG$pos,
                  y = consDF_SIG$DIFF,
                  text = paste(consDF_SIG$seq,consDF_SIG$pos, sep=""),
                  xref = "x",
                  yref = "y",
                  showarrow = TRUE,
                  arrowhead = 4,
                  arrowsize = .5,
                  ax = 20,
                  ay = -20,
                  font = list(color = 'grey',
                              family = 'sans serif',
                              size = 12))%>%
  layout(xaxis = list(title = 'Alignment Position'),
         yaxis = list(title = 'Difference in conservation'))
p1


# Plotting a 1 dimensional smoothed heatmap of the overall conservation score for each residue
df <- data.frame(x=conscore_all$POS, y=conscore_all$SCORE_abs)
newdf=data.frame(x=spline(df)[[1]],freq=spline(df)[[2]],y=rep(1,times=3*length(df$x)))

svg("1dheatmap_all_conservation.svg", height = 1, width = 10)
ggplot(newdf,aes(x=x,y=y,fill=freq))+
  geom_tile()+
  theme(axis.title.x = element_blank(),axis.title.y = element_blank(), axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  labs(fill = "Relative\nresidue\nconservation")
dev.off()
        